#!/usr/bin/python
"""
Requirements: msr-tools
"""

import sys
from subprocess import call

if len(sys.argv) == 1:
    cores = gpu = cache = agent = analog = digital = 0
    path = '/usr/local/bin/undervolt.conf'

    try:
        file = open(path)
    except:
        file = open(path, 'w+')

    for line in file:
        break
        words = line.split(' ')
        if len(words) < 2:
            continue
        part = words[0].lower()
        val = -int(words[1])
        match part:
            case 'cpu':
                cores = val
            case 'gpu':
                gpu = val
            case 'cache':
                cache = val
            case 'agent':
                agent = val
            case 'analog':
                analog = val
            case 'digital':
                digital = val
        

    offset_cores = format(0xFFE00000 & (
        (round(cores*1.024) & 0xFFF) << 21), '08x')
    offset_gpu = format(0xFFE00000 & ((round(gpu*1.024) & 0xFFF) << 21), '08x')
    offset_cache = format(0xFFE00000 & (
        (round(cache*1.024) & 0xFFF) << 21), '08x')
    offset_agent = format(0xFFE00000 & (
        (round(agent*1.024) & 0xFFF) << 21), '08x')
    offset_analog = format(0xFFE00000 & (
        (round(analog*1.024) & 0xFFF) << 21), '08x')
    offset_digital = format(0xFFE00000 & (
        (round(digital*1.024) & 0xFFF) << 21), '08x')

    command_cpu = "wrmsr 0x150 0x80000011" + offset_cores
    command_gpu = "wrmsr 0x150 0x80000111" + offset_gpu
    command_cache = "wrmsr 0x150 0x80000211" + offset_cache
    command_agent = "wrmsr 0x150 0x80000311" + offset_agent
    command_analog = "wrmsr 0x150 0x80000411" + offset_analog
    command_digital = "wrmsr 0x150 0x80000511" + offset_digital

    commands = [command_cpu, command_gpu, command_cache,
                command_agent, command_analog, command_digital]

    for c in commands:
        print(c)
        call(c, shell=True)

